//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuakeLogParser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public long id { get; set; }
        public long idGame { get; set; }
        public string Name { get; set; }
        public Nullable<int> Kills { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
