-- MySQL Script generated by MySQL Workbench
-- 09/30/17 15:28:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema QuakeLogParser
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `QuakeLogParser` ;

-- -----------------------------------------------------
-- Schema QuakeLogParser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuakeLogParser` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `QuakeLogParser` ;

-- -----------------------------------------------------
-- Table `Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Game` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Game` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Name` TEXT NULL,
  `TotalKills` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Player` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Player` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `idGame` BIGINT NOT NULL,
  `Name` TEXT NULL,
  `Kills` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Player_Game`
    FOREIGN KEY (`idGame`)
    REFERENCES `Game` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Player_Game_idx` ON `Player` (`idGame` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
